{{- if and (.Values.flinkOperatorCrds) (.Values.flinkOperatorCrds.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator-skip-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/flink-kubernetes-operator
    targetRevision: {{ .Values.targetRevision }}
    helm:
      skipCRDs: true
      # parameters:
      # - name: aws-for-fluent-bit.cloudWatch.region
      #   value: {{ .Values.region }}
      # - name: aws-for-fluent-bit.serviceAccount.name
      #   value: {{ .Values.awsForFluentBit.serviceAccountName }}
      # - name: aws-for-fluent-bit.cloudWatch.serviceAccount.name
      #   value: {{ .Values.awsForFluentBit.serviceAccountName }}
      # - name: aws-for-fluent-bit.cloudWatch.logGroupName
      #   value: {{ .Values.awsForFluentBit.logGroupName }}
      # - name: aws-for-fluent-bit.firehose.region
      #   value: {{ .Values.region }}
      # - name: aws-for-fluent-bit.kinesis.region
      #   value: {{ .Values.region }}
      # - name: aws-for-fluent-bit.elasticsearch.region
      #   value: {{ .Values.region }}
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-operator
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}